MyNews/urls.py
from django.contrib import admin
from django.urls import path, include, re_path
from django.conf.urls.static import static
from django.conf import settings

urlpatterns = [
    path('admin/', admin.site.urls), 
    path('', include('stories.urls')),
    re_path(r'^ckeditor/', include('ckeditor_uploader.urls')),
    #path('stories/', include('stories.urls')),   
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

stories/urls.py
from django.urls import path
from . import views
app_name = 'stories'
urlpatterns = [
    path('', views.index, name='index'),
    path('category.html/<int:pk>/', views.category, name='category.html'),
    path('story.html/<int:pk>/', views.story, name='story.html'),
    path('contact.html', views.contact, name='contact.html'),
]

stories/models.py
from django.db import models
import datetime
from ckeditor.fields import RichTextField
from ckeditor_uploader.fields import RichTextUploadingField

class Category(models.Model):
    name = models.CharField(max_length=150, unique=True)

    def __str__(self):
        return self.name


class Story(models.Model):
    category = models.ForeignKey(Category, on_delete=models.PROTECT)
    name = models.CharField(max_length=250, unique=True)
    author = models.CharField(max_length=250)
    url = models.URLField(null=True)
    content = RichTextUploadingField()
    public_day = models.DateField(default=datetime.date.today)
    image = models.ImageField(upload_to="stories/images", default="stories/images/default.jpg")


    def __str__(self):
        return str(self.id) + " " + self.name + " " + str(self.category.id)

stories/views.py
import datetime
from datetime import date
from django.shortcuts import render
from .models import Category, Story
from django.http import HttpResponse
import re
from django.core.paginator import Paginator, EmptyPage, PageNotAnInteger


now = datetime.datetime.now()
today = date.today()
d1 = today.strftime("%b. %d,%Y")

def index(request):
    story_list = Story.objects.order_by("-id")
    newest = story_list[0]
    next_4_newest = story_list[1:5]
    newest_list = story_list[0:4]
    most_viewed_stories = story_list[3:6]

    young_children = Story.objects.filter(category=1).order_by("-id")
    older_children = Story.objects.filter(category=2).order_by("-id")
    
    return render(request, "stories/index.html", 
                {'today':now,
                'd1': d1,
                'newest': newest,
                'next_4_newest': next_4_newest,
                'newest_list': newest_list,
                'young': young_children,
                'older': older_children,
                'most_viewed_stories': most_viewed_stories,})

def category(request, pk):
    story_list = Story.objects.filter(category=pk).order_by("-id")
    for story in story_list:
        story.content = re.sub('<[^<]+?>', '', story.content)

    page = request.GET.get('page', 1) # trang bắt đầu    

    paginator = Paginator(story_list, 3) # số story/trang


    
    try:
        stories = paginator.page(page)
    except PageNotAnInteger:
        stories = paginator.page(1)
    except EmptyPage:
        stories = paginator.page(paginator.num_pages)


    newest = Story.objects.filter(category=pk).order_by("-id")[0]
    newest_stories = Story.objects.filter(category=pk).order_by("-id")[0:4]
    most_viewed_stories = Story.objects.order_by("-id")[3:6]

    return render(request, "stories/category.html", 
                {'today':now,
                'stories': stories,
                'newest': newest,
                'pk': pk,
                'newest_stories': newest_stories,
                'most_viewed_stories': most_viewed_stories,
                })

def story(request, pk):
    story_select = Story.objects.get(pk=pk)
    stories = Story.objects.filter(category=story_select.category).order_by("-id")
    newest = Story.objects.order_by("-id")[0]
    newest_stories = Story.objects.order_by("-id")[0:4]
    most_viewed_stories = Story.objects.order_by("-id")[3:6]
    return render(request, "stories/story.html", 
                {'today':now,
                'story': story_select,
                'stories': stories,
                'newest': newest,
                'newest_stories': newest_stories,
                'most_viewed_stories': most_viewed_stories,
                })

def contact(request):
    newest = Story.objects.order_by("-id")[0]
    newest_stories = Story.objects.order_by("-id")[0:4]
    most_viewed_stories = Story.objects.order_by("-id")[3:6]
    return render(request, "stories/contact.html", {'today':now, 'newest': newest, 'newest_stories': newest_stories, 'most_viewed_stories': most_viewed_stories})
    

stories/templates/stories/story.html
<!DOCTYPE html>
<!--
	24 News by FreeHTML5.co
	Twitter: https://twitter.com/fh5co
	Facebook: https://fb.com/fh5co
	URL: https://freehtml5.co
-->
{% load static %}
<script type="text/javascript" src="{% static "ckeditor/ckeditor-init.js" %}"></script>
<script type="text/javascript" src="{% static "ckeditor/ckeditor/ckeditor.js" %}"></script>
<html lang="en" class="no-js">
<head>
    <!-- Required meta tags -->
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Stories for Children</title>  
    <link href='{% static "stories/css/media_query.css" %}' rel="stylesheet" type="text/css"/>
    <link href='{% static "stories/css/bootstrap.css" %}' rel="stylesheet" type="text/css"/>
    <link href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" rel="stylesheet"
          integrity="sha384-wvfXpqpZZVQGK6TAh5PVlGOfQNHSoD2xbE+QkPxCAFlNEevoEH3Sl0sibVcOQVnN" crossorigin="anonymous">
    <link href='{% static "stories/css/animate.css"%}' rel="stylesheet" type="text/css"/>
    <link href='{% static "stories/css/owl.carousel.css"%}' rel="stylesheet" type="text/css"/>
    <link href='{% static "stories/css/owl.theme.default.css"%}' rel="stylesheet" type="text/css"/>
    <!-- Bootstrap CSS -->
    <link href='{% static "stories/css/style_1.css"%}' rel="stylesheet" type="text/css"/>
    <!-- Modernizr JS -->
    <script src='{% static "stories/js/modernizr-3.5.0.min.js"%}'></script>
    

</head>
<body>
<div class="container-fluid">
    <div class="container">
        <div class="row">
            <div class="col-12 col-md-3 fh5co_padding_menu">
                <img src='{% static "stories/images/logo_1986_N.png"%}' alt="img" class="fh5co_logo_width"/>
            </div>
            <div class="col-12 col-md-9 align-self-center fh5co_mediya_right">
                <div class="text-center d-inline-block">
                    <a class="fh5co_display_table"><div class="fh5co_verticle_middle"><i class="fa fa-search"></i></div></a>
                </div>	
                
                <!--<div class="d-inline-block text-center"><img src="images/country.png" alt="img" class="fh5co_country_width"/></div>-->                
				
				<div class="text-center d-inline-block">
                    <a>&nbsp;&nbsp;&nbsp;{{today}}</a>
                </div>
				
                <div class="clearfix"></div>		
				
            </div>
        </div>
    </div>
</div>
<div class="container-fluid bg-faded fh5co_padd_mediya padding_786">
    <div class="container padding_786">
        <nav class="navbar navbar-toggleable-md navbar-light ">
            <button class="navbar-toggler navbar-toggler-right mt-3" type="button" data-toggle="collapse"
                    data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false"
                    aria-label="Toggle navigation"><span class="fa fa-bars"></span></button>
            <a class="navbar-brand" href="#"><img src='{% static "stories/images/logo.png"%}' alt="img" class="mobile_logo_width"/></a>
            <div class="collapse navbar-collapse" id="navbarSupportedContent">
                <ul class="navbar-nav mr-auto">
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'stories:index'%}">Home <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'stories:category.html' 1 %}">Young Children <span class="sr-only">(current)</span></a>
                    </li>
					<li class="nav-item ">
                        <a class="nav-link" href="{% url 'stories:category.html' 2 %}">Older Children <span class="sr-only">(current)</span></a>
                    </li>
                    <li class="nav-item active">
                        <a class="nav-link" href="{% url 'stories:story.html' newest.pk %}">Story <span class="sr-only">(current)</span></a>
                    </li>                    
                    <li class="nav-item ">
                        <a class="nav-link" href="{% url 'stories:contact.html'%}">Contact <span class="sr-only">(current)</span></a>
                    </li>
                </ul>
            </div>
        </nav>
    </div>
</div>

<div id="fh5co-single-content" class="container-fluid pb-4 pt-4 paddding">    
    <div class="container paddding">
        <div class="row mx-0"> 
            <div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">       
                <h2>{{ story.name }}</h2> 
                <span>Written and Illustrated by {{ story.author }}</span>
                <div>
                    <img src="{{ story.image.url }}" alt="{{ story.name }}" />
                </div>
            </div>
        </div>
    </div>
</div>

<div id="fh5co-single-content" class="container-fluid pb-4 pt-4 paddding">
    <div class="container paddding">
        <div class="row mx-0">
            <div class="col-md-12 animate-box" data-animate-effect="fadeInLeft">
                {% comment %} {{ story.content|safe }} {% endcomment %}
				<p>{{ story.content|safe }}</p>
                <p><a href="{{ story.url }}">{{ story.url }}</a></p>
            </div>
            
        </div>
    </div>
</div>
<div class="container-fluid pb-4 pt-5">
    <div class="container animate-box">
        <div>
            <div class="fh5co_heading fh5co_heading_border_bottom py-2 mb-4">New Stories</div>
        </div>
        <div class="owl-carousel owl-theme" id="slider2">
            
            {% for story in newest_stories %}
            <div class="item px-2">
                <div class="fh5co_hover_news_img">
                    <div class="fh5co_news_img"><img src="{{ story.image.url }}" alt="{{ story.name }}"/></div>
                    <div>
                        <a href="{% url 'stories:story.html' story.id %}" class="d-block fh5co_small_post_heading"><span class="">{{ story.name }}</span></a>
                        <div class="c_g"><i class="fa fa-clock-o"></i> {{ story.public_day }}</div>
                    </div>
                </div>
            </div>
            {% endfor %}
            
            
            {% comment %} <div class="item px-2">
                <div class="fh5co_hover_news_img">
                    <div class="fh5co_news_img"><img src='{% static "stories/images/Unthingables.jpg"%}' alt=""/></div>
                    <div>
                        <a href="#" class="d-block fh5co_small_post_heading"><span class="">Un Thing Ables</span></a>
                        <div class="c_g"><i class="fa fa-clock-o"></i> Oct 16,2020</div>
                    </div>
                </div>
            </div>
            <div class="item px-2">
                <div class="fh5co_hover_news_img">
                    <div class="fh5co_news_img"><img src='{% static "stories/images/Unthingables.jpg"%}' alt=""/></div>
                    <div>
                        <a href="#" class="d-block fh5co_small_post_heading"><span class="">Un Thing Ables</span></a>
                        <div class="c_g"><i class="fa fa-clock-o"></i> Oct 16,2020</div>
                    </div>
                </div>
            </div>
            <div class="item px-2">
                <div class="fh5co_hover_news_img">
                    <div class="fh5co_news_img"><img src='{% static "stories/images/Unthingables.jpg"%}' alt=""/></div>
                    <div>
                        <a href="#" class="d-block fh5co_small_post_heading"><span class="">Un Thing Ables</span></a>
                        <div class="c_g"><i class="fa fa-clock-o"></i> Oct 16,2020</div>
                    </div>
                </div>
            </div>
            <div class="item px-2">
                <div class="fh5co_hover_news_img">
                    <div class="fh5co_news_img"><img src="images/Unthingables.jpg" alt=""/></div>
                    <div>
                        <a href="#" class="d-block fh5co_small_post_heading"><span class="">Un Thing Ables</span></a>
                        <div class="c_g"><i class="fa fa-clock-o"></i> Oct 16,2020</div>
                    </div>
                </div>
            </div> {% endcomment %}
        </div>
    </div>
</div>

<div class="container-fluid fh5co_footer_bg pb-3">
    <div class="container animate-box">
        <div class="row">
            <div class="col-12 spdp_right py-5"><img src='{% static "stories/images/logo_1986_N.png"%}' alt="img" class="footer_logo"/></div>
            <div class="clearfix"></div>
            <div class="col-12 col-md-4 col-lg-3">
                <div class="footer_main_title py-3"> About</div>
                <div class="footer_sub_about pb-3"> This website is designed specifically for children who love reading and learning good things from the books.
							Website references data from a number of sites like: https://www.freechildrenstories.com/, 
							http://www.magickeys.com/books/
                </div>               
            </div>
            <div class="col-12 col-md-3 col-lg-2">
                <div class="footer_main_title py-3"> Category</div>
                <ul class="footer_menu">
                    <li><a href="{% url 'stories:category.html' 1 %}" class=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp; Young Children</a></li>
                    <li><a href="{% url 'stories:category.html' 2 %}" class=""><i class="fa fa-angle-right"></i>&nbsp;&nbsp; Older Children</a></li>                               
                </ul>
            </div>
            <div class="col-12 col-md-5 col-lg-3 position_footer_relative">
                <div class="footer_main_title py-3"> Most Viewed Stories</div>
                {% for story in most_viewed_stories %}
                <div class="footer_makes_sub_font"> {{ story.public_day}}</div>
                <a href="{% url 'stories:story.html' story.id %}" class="footer_post pb-4"> {{ story.name }} </a> 
                {% endfor %}

                {% comment %} <div class="footer_makes_sub_font"> Dec 31, 2016</div>
                <a href="#" class="footer_post pb-4"> First Story </a>
                <div class="footer_makes_sub_font"> Dec 31, 2016</div>
                <a href="#" class="footer_post pb-4"> Second Story </a>
                <div class="footer_makes_sub_font"> Dec 31, 2016</div>
                <a href="#" class="footer_post pb-4"> Third Story </a> {% endcomment %}
            </div>
            <div class="col-12 col-md-12 col-lg-4 ">
                <div class="footer_main_title py-3"> Newest Stories</div>
                {% for story in newest_stories %}
                    <a href="#" class="footer_img_post_6"><img src='{{ story.image.url }}' alt="{{ story.name }}"/></a>
                {% endfor %}
                {% comment %} <a href="#" class="footer_img_post_6"><img src='{% static "stories/images/32-450x260.jpg"%}' alt="img"/></a>
                <a href="#" class="footer_img_post_6"><img src='{% static "stories/images/download (1).jpg"%}' alt="img"/></a>
                <a href="#" class="footer_img_post_6"><img src='{% static "stories/images/science-578x362.jpg"%}' alt="img"/></a> {% endcomment %}
            </div>
        </div>
        <div class="row justify-content-center pt-2 pb-4">
            <div class="col-12 col-md-8 col-lg-7 ">
                <div class="input-group">
                    <span class="input-group-addon fh5co_footer_text_box" id="basic-addon1"><i class="fa fa-envelope"></i></span>
                    <input type="text" class="form-control fh5co_footer_text_box" placeholder="Enter your email..." aria-describedby="basic-addon1">
                    <a href="#" class="input-group-addon fh5co_footer_subcribe" id="basic-addon12"> <i class="fa fa-paper-plane-o"></i>&nbsp;&nbsp;Subscribe</a>
                </div>
            </div>
        </div>
    </div>
</div>
<div class="container-fluid fh5co_footer_right_reserved">
    <div class="container">
        <div class="row  ">
            <div class="col-12 col-md-6 py-4 Reserved"> © Copyright 2018, All rights reserved. Design by <a href="https://freehtml5.co" title="Free HTML5 Bootstrap templates">FreeHTML5.co</a>. </div>
            <div class="col-12 col-md-6 spdp_right py-4">
                <a href="{% url 'stories:index' %}" class="footer_last_part_menu">Home</a>
                <a href="{% url 'stories:contact.html' %}" class="footer_last_part_menu">About</a>
                <a href="{% url 'stories:contact.html' %}" class="footer_last_part_menu">Contact</a>               
        </div>
    </div>
</div>

<div class="gototop js-top">
    <a href="#" class="js-gotop"><i class="fa fa-arrow-up"></i></a>
</div>

<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
<script src='{% static "stories/js/owl.carousel.min.js"%}'></script>
<!--<script src="https://code.jquery.com/jquery-3.1.1.slim.min.js" integrity="sha384-A7FZj7v+d/sdmMqp/nOQwliLvUsJfDHW+k9Omg/a/EheAdgtzNs3hpfag6Ed950n" crossorigin="anonymous"></script>-->
<script src="https://cdnjs.cloudflare.com/ajax/libs/tether/1.4.0/js/tether.min.js"
        integrity="sha384-DztdAPBWPRXSA/3eYEEUWrWCy7G5KFbe8fFjk5JAIxUYHKkDx6Qin1DkWx51bBrb"
        crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0-alpha.6/js/bootstrap.min.js"
        integrity="sha384-vBWWzlZJ8ea9aCX4pEW3rVHjgjt7zpkNpZk+02D9phzyeVkE+jo0ieGizqPLForn"
        crossorigin="anonymous"></script>
<!-- Waypoints -->
<script src='{% static "stories/js/jquery.waypoints.min.js"%}'></script>
<!-- Main -->
<script src='{% static "stories/js/main.js"%}'></script>

</body>
</html>